### PR TITLE
use find/basename to find RPMs to upload

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by ekohl** [comment]
Looking a bit closer: have you tested this? Looking at this I wonder if the relative path works without the cd. basename strips away the directory not just the extension.

**Comment by evgeni** [comment]
yes. the RPMs are not *really* uploaded, they are just *written* on koji.

**Comment by ekohl** [comment]
Right, so we should rename the script to write_signed_rpms to be clearer.

**Comment by evgeni** [comment]
`<ewoud> naming is hard`

**Comment by evgeni** [comment]
We could also pass `--write` to `import-sigs`, then this step wouldn't be needed at all anymore?

**Comment by ekohl** [comment]
Honestly, for this part I mostly used what was handed over to me.

image

**Pull request merged**
